### ISSUE TITLE
1.17 Error: "Could not execute entrypoint stage 'main' due to errors, provided by 'phonos' "

### ISSUE THREAD

**Issue by MindForged** [FoundationGames/Phonos#14]
The server log says the following after the title error:

`
[Server] INFO at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric_1.17.jar:?]
07.07 22:04:11 [Server] INFO at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric_1.17.jar:?]
07.07 22:04:11 [Server] INFO at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric_1.17.jar:?]
07.07 22:04:11 [Server] INFO at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
07.07 22:04:11 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
07.07 22:04:11 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
07.07 22:04:11 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
07.07 22:04:11 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
07.07 22:04:11 [Server] INFO at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric_1.17.jar:?]
07.07 22:04:11 [Server] INFO at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric_1.17.jar:?]
07.07 22:04:11 [Server] INFO at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric_1.17.jar:?]
07.07 22:04:11 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
07.07 22:04:11 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
07.07 22:04:11 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
07.07 22:04:11 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
07.07 22:04:11 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric_1.17.jar:?]
07.07 22:04:11 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric_1.17.jar:?]
07.07 22:04:11 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric_1.17.jar:?]
07.07 22:04:11 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_5810
07.07 22:04:11 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
07.07 22:04:11 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
07.07 22:04:11 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
07.07 22:04:11 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163) ~[fabric_1.17.jar:?]
07.07 22:04:11 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
`

**Comment by triphora** [comment]
phonos for 1.17 isn't out yet

**Comment by MindForged** [comment]
Oh crud. CurseForge has it listed as 1.17, should've noticed the release date. Guess I'll be patient, haha
