### ISSUE TITLE
Dedicated server crash - java.lang.NoSuchMethodError: net.minecraft.class_3414.method_14833()Lnet/minecraft/class_2960;

### ISSUE THREAD

**Issue by ProsperCraft** [FoundationGames/Phonos#2]
https://gist.github.com/ProsperCraft/92751eae2d19cd14b2b9537d78714c67
Put a disc in a jukebox and press play.

**Comment by FoundationGames** [comment]
This is really odd... Phonos has worked fine on the ModFest server without issues, yet here it's not finding that method on your dedicated server? Strange... I think I will be able to fix this issue though.

**Comment by jgshaban** [comment]
Don't know if it'll help any or not, but I've been having the same issue with the radio jukebox. I'm also running a dedicated minecraft server like ProsperCraft is. However, I suspect ProsperCraft and I don't have the same mods loaded. I have a link to the crash report below.

Some more information for you, if it helps:

- This server is running the All of Fabric 3 modpack. This mod is not running by itself in vanilla.
- Two seperate players on the server were able to cause this server crash by adding a disc to the radio jukebox, and pressing play like previously mentioned.
- The error occurs when using both Oracle JRE and Open JRE
- The host OS for this minecraft instance is OpenSuse Leap 15.2

I'd be happy to provide more information if you need it.

[crash-2020-11-29_17.35.01-server.txt](https://github.com/FoundationGames/Phonos/files/5613452/crash-2020-11-29_17.35.01-server.txt)

**Comment by Giggitybyte** [comment]
This exception is also thrown on my server instance as well.
https://paste.thegiggitybyte.me/nBUuKMAsrs

**Comment by dandin87** [comment]
Same Crash on the All Of Fabric 3 Public Servers.
https://hastebin.com/zoqizovato.yaml

**Comment by Giggitybyte** [comment]
After debugging this project, it looks like [`SoundEvent.getId()`](https://github.com/FoundationGames/Phonos/blob/master/src/main/java/io/github/foundationgames/phonos/network/PayloadPackets.java#L31) is a client sided method, which causes an exception and a crash when used on a dedicated server.

https://paste.thegiggitybyte.me/bDEGenKTlV

**Comment by BloodTiger** [comment]
I have same issue. @FoundationGames, can you fix this? This mod is wonderful and we always wanted autoplay jukebox on our server.

**Comment by Dadadah** [comment]
I encountered this issue as well. I fixed it to get my dedicated server to stop crashing when I connected. @FoundationGames please review this PR ASAP to get this fix into the AOF 3 modpack. Thanks.

**Comment by Lhruggles** [comment]
also getting this bug

**Comment by FoundationGames** [comment]
Was fixed in 0.1.1, Thanks for the bug report!
