### ISSUE TITLE
Vanilla music disc doesn't play?

### ISSUE THREAD

**Issue by Derpford** [FoundationGames/Phonos#3]
For some reason, the vanilla discs won't play in the Phonos jukebox, but will play just fine in the vanilla one. Discs from the Backrooms mod work just fine, though...

**Comment by FoundationGames** [comment]
Really? Could you possibly show a video of the bug? In my experience, the vanilla discs work even with other mods installed

**Comment by FoundationGames** [comment]
This may also be a compat issue, another one of your mods must be messing with vanilla discs. Please provide more context, possibly with your mod list.

**Comment by FoundationGames** [comment]
If I don't recieve further clarification on this issue, I will close it. Thanks for the report!

**Comment by FoundationGames** [comment]
Closed due to lack of information.
