### ISSUE TITLE
loading crash.

### ISSUE THREAD

**Issue by netcore10** [FoundationGames/Phonos#32]
I've tried to find the issue, but i cant seem to figure it out, can you discern why it's crashing?

[crash-2022-05-22_17.28.42-client.txt](https://github.com/FoundationGames/Phonos/files/8749792/crash-2022-05-22_17.28.42-client.txt)

[latest.log](https://github.com/FoundationGames/Phonos/files/8749793/latest.log)

**Comment by BobaBath** [comment]
I'm having this issue too, for me it's an endless loading screen that resets every time it reaches the title screen. My log also shows the "Exception loading blockstate definition" and "Unable to resolve texture reference" errors.

**Comment by MScott7** [comment]
I think I'm having this issue, and its becoming quite bizarre. Firstly, I believe that the logs posted previously describe an issue of the Chimes mod having a capital letter in the path, something that the [creator seems to be aware of](https://www.curseforge.com/minecraft/mc-mods/chimes?comment=168). 

When I disable Chimes though, I get seemingly the same issue of the game infinitely loading and restarting. This time the log seems to blame the Waystones mod. When I disable Chimes and Waystones the game loads fine. I don't know why Waystones conflicts with Phonos but I'll post both logs anyways. Both runs were ended by me closing the game, so it didn't technically crash for me.

latest.log with Chimes and Waystones: https://pastebin.com/1VqJniiH
latest.log without Chimes and with Waystones: https://pastebin.com/rfcwEy8v

**Comment by FoundationGames** [comment]
The issue with Chimes is known, and a fix would be best suited to be added by Chimes itself
I could definitely add more detailed error handling to JsonEM (where the issue occurs), and because of this the issue probably isn't relevant to Phonos anymore.

**Comment by MScott7** [comment]
Only the first error is related to jsonEM, right? 
The second error mentioning Waystones doesn't mention JsonEM at all and is fully unrelated to Chimes. I would think that that one is relevant to Phonos as Waystones works fine when it's not present.
